framework:
    messenger:
        # Transport dla nieudanych wiadomości
        failure_transport: failed

        transports:
            # Transport asynchroniczny — Redis
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # Transport dla nieudanych wiadomości
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            App\Message\TicketClosedMessage: async

# when@test:
#    framework:
#        messenger:
#            transports:
#                async: 'in-memory://'
