<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260605214311 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE devices (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, serial_number VARCHAR(100) NOT NULL, model VARCHAR(150) NOT NULL, customer_name VARCHAR(200) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11074E9AD948EE2 ON devices (serial_number)');
        $this->addSql('CREATE TABLE technicians (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_63FB4240E7927C74 ON technicians (email)');
        $this->addSql('CREATE TABLE ticket_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, old_status VARCHAR(255) DEFAULT NULL, new_status VARCHAR(255) NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, changed_by VARCHAR(200) NOT NULL, ticket_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B762919700047D2 ON ticket_history (ticket_id)');
        $this->addSql('CREATE TABLE tickets (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, priority VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, assigned_technician_id INT DEFAULT NULL, device_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_54469DF45CF77DD3 ON tickets (assigned_technician_id)');
        $this->addSql('CREATE INDEX IDX_54469DF494A4C7D4 ON tickets (device_id)');
        $this->addSql('ALTER TABLE ticket_history ADD CONSTRAINT FK_2B762919700047D2 FOREIGN KEY (ticket_id) REFERENCES tickets (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tickets ADD CONSTRAINT FK_54469DF45CF77DD3 FOREIGN KEY (assigned_technician_id) REFERENCES technicians (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tickets ADD CONSTRAINT FK_54469DF494A4C7D4 FOREIGN KEY (device_id) REFERENCES devices (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ticket_history DROP CONSTRAINT FK_2B762919700047D2');
        $this->addSql('ALTER TABLE tickets DROP CONSTRAINT FK_54469DF45CF77DD3');
        $this->addSql('ALTER TABLE tickets DROP CONSTRAINT FK_54469DF494A4C7D4');
        $this->addSql('DROP TABLE devices');
        $this->addSql('DROP TABLE technicians');
        $this->addSql('DROP TABLE ticket_history');
        $this->addSql('DROP TABLE tickets');
    }
}
